### ISSUE TITLE
Doesn't allow backslashes in bug report view

### ISSUE THREAD

**Issue by soybean26** [a-v-k/phpBugTracker#9]
When the tracker pulls the data from the DB the bug view strips away the backslashes, I was wondering if there was a way to allow them? 
![bugtracker_screen](https://cloud.githubusercontent.com/assets/8020751/9821650/ec85bb60-5878-11e5-9665-207f37c70cfb.png)

**Comment by a-v-k** [comment]
I can't reproduce the bug.
What version of phpBugTracker do you use?
If you use the old version - please upgrade to modern version first. Modern versions uses the new DB library. And it must not have a problems.

**Comment by soybean26** [comment]
It looks like I'm using 1.0.5 2009 Sep. I'll test out the new version on a
UAT, but I believe that the issue I'm experiencing is with the
stripslashes.

**Comment by a-v-k** [comment]
1.0.5 is a very very old discontinued version that was made by the previous developer.
That version was have a very many problems. Since then, I have fixed a lot of bugs. I can’t help you with so oldest version.
Please upgrade your codebase to modern version first.

And, as I see, you have a not original but customized version of tracker. Problem can be in the customized code too.

If you have a customized version, you can run into problems when upgrading. If so, I can offer a paid support for upgrade.
